import java.awt.Color;
import javax.swing.ImageIcon;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import javax.swing.JButton;
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class Frame3 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Cinema_system.class.getName());
    /**
     * Creates new form Cinema_system
     */public static String selectedMovie;
    public static String selectedUser;
    
    private JButton selectedButton=null;
    Border redBorder=BorderFactory.createLineBorder(Color.RED,3);
    Border emptyBorder=BorderFactory.createEmptyBorder();
  private String currentUser;
    public Frame3() {
        initComponents();
        setPreferredSize(new java.awt.Dimension(650,380));
        setSize(650,380);
        setLocationRelativeTo(null);
        
         currentUser = Frame2.userName;
         selectedUser = currentUser;
         
         
        barbieButton.setIcon(resizeIcon(getClass().getResource("/images/barbie.jpg"),100,110));
        barbieButton.setText("");
        barbieButton.setContentAreaFilled(false);
        barbieButton.setBorderPainted(true);
        
        superButton.setIcon(resizeIcon(getClass().getResource("/images/superMan.jpg"),100,110));
        superButton.setText("");
        superButton.setContentAreaFilled(false);
        superButton.setBorderPainted(true);
        
        jButton6.setIcon(resizeIcon(getClass().getResource("/images/bladerunner.jpg"),100,110));
        jButton6.setText("");
        jButton6.setContentAreaFilled(false);
        jButton6.setBorderPainted(true);
        
        jButton7.setIcon(resizeIcon(getClass().getResource("/images/wiked.jpg"),100,110));
        jButton7.setText("");
        jButton7.setContentAreaFilled(false);
        jButton7.setBorderPainted(true);
        
        jButton3.setIcon(resizeIcon(getClass().getResource("/images/TheConjuring.jpg"),100,110));
        jButton3.setText("");
        jButton3.setContentAreaFilled(false);
        jButton3.setBorderPainted(true);
        }
    
    public ImageIcon resizeIcon(java.net.URL path,int width,int height){
        ImageIcon icon=new ImageIcon(path);
        Image img=icon.getImage();
        Image resizedImage=img.getScaledInstance(width, height, Image.SCALE_SMOOTH);
        return new ImageIcon(resizedImage);
    }
    
    private void saveBooking(String movieName) {
        try {
            Connection con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/cinema_system", "root", "181960hobyou#00#p18");

            String sql = "INSERT INTO booking_details(Name, Movie, Day, Snacks, Time, Seats, Payment) " +
                    "VALUES (?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, currentUser);// Name
            pst.setString(2, movieName);  // Movie 
            pst.setString(3, "TBD");    // Day   
            pst.setString(4, "None");// Snacks
            pst.setString(5, "TBD");// Time
            pst.setString(6, "TBD");// Seats
            pst.setString(7, "TBD"); // Payment

            pst.executeUpdate();
           
            con.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error saving booking: " + ex.getMessage());
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        barbieButton = new javax.swing.JButton();
        superButton = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(600, 800));
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 0));
        jButton1.setText("<-Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 320, 80, 27);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 0, 0));
        jButton2.setText("Next->");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(560, 320, 78, 27);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Your Booking Details");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 30, 240, 32);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Choose Your Movie:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 70, 120, 16);

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(370, 200, 100, 110);

        barbieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barbieButtonActionPerformed(evt);
            }
        });
        getContentPane().add(barbieButton);
        barbieButton.setBounds(70, 90, 100, 110);

        superButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        superButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                superButtonActionPerformed(evt);
            }
        });
        getContentPane().add(superButton);
        superButton.setBounds(260, 90, 110, 110);

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(460, 90, 100, 110);

        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(160, 200, 100, 110);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Barbie");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(96, 200, 40, 18);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SuperMan");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(290, 200, 60, 18);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("BladeRunner");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(480, 200, 80, 18);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Wiked:for good");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(160, 310, 100, 18);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("TheConjuring");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(380, 310, 80, 18);

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 650, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Frame2 frame2=new Frame2();
     frame2.setVisible(true);
     dispose();// TODO add your handling code here:
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     if(selectedButton!=null){
         selectedButton.setBorder(emptyBorder);}
     jButton3.setBorder(redBorder);
     selectedButton=jButton3;   // TODO add your handling code here:
     selectedMovie = "TheConjuring";
     saveBooking("TheConjuring");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void superButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_superButtonActionPerformed
     if(selectedButton!=null){
         selectedButton.setBorder(emptyBorder);}
     superButton.setBorder(redBorder);
     selectedButton=superButton;// TODO add your handling code here:
     selectedMovie = "SuperMan";
     saveBooking("SuperMan");
    }//GEN-LAST:event_superButtonActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
     if(selectedButton!=null){
         selectedButton.setBorder(emptyBorder);}
     jButton6.setBorder(redBorder);
     selectedButton=jButton6;         // TODO add your handling code here:
     selectedMovie = "BladeRunner";
      saveBooking("BladeRunner");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
     if(selectedButton!=null){
         selectedButton.setBorder(emptyBorder);}
     jButton7.setBorder(redBorder);
     selectedButton=jButton7;  
     jButton7.setBorder(BorderFactory.createLineBorder(Color.RED,3));  // TODO add your handling code here:
       selectedMovie = "Wicked:for good";
     saveBooking("Wicked:for good"); 
    }//GEN-LAST:event_jButton7ActionPerformed

    private void barbieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barbieButtonActionPerformed
     if(selectedButton!=null){
         selectedButton.setBorder(emptyBorder);}
     barbieButton.setBorder(redBorder);
     selectedButton=barbieButton;// TODO add your handling code here:
      selectedMovie = "Barbie";
      saveBooking("Barbie");
    }//GEN-LAST:event_barbieButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 Frame4 frame4=new Frame4();
     frame4.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Cinema_system().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barbieButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton superButton;
    // End of variables declaration//GEN-END:variables
}
